image: python:3.9

stages:
  - test_py

test_py:
  stage: test_py
  coverage: '/^Code coverage:\s\d+$/'
  cache:
    key: bulksms_cache
    paths:
      - venv/
      - .cache/pip/
      - urlcache.csv
  script:
    # setup: base system
    - WD=$(pwd)
    - echo "Working directory is $WD"
    - echo "Creating venv ..."
    - test venv -nt .gitlab-ci.yml || python -m venv venv
    - . venv/bin/activate
    - pip install -r ${WD}/src/docs/requirements_test.txt
    - pip freeze
    - cd ${WD}/src/bulksms
    - PYTHONPATH=.:${WD}/src coverage run -m unittest discover
    ## print coverage information
    - cd $WD
    - coverage combine $(find . -name .coverage)
    - printf 'Code coverage:\t' ; coverage report --omit='**/tests/**' --format=total --precision=0 ; echo ""
    ## packaging
    - echo "bulksms packaging"
    - cd ${WD}
    - pip install build
    - python -m build
    - pip install dist/bulksms-1.1.0-py3-none-any.whl
    - echo "Validate entrypoint scripts with 'which'"
    - which bulksms
